# Generated by Django 3.2.8 on 2021-11-12 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0002_alter_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.TextField()),
                ('account_money', models.TextField()),
                ('bank', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='mbti',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('payment', models.TextField()),
                ('date', models.DateField(default='1112')),
                ('paylink', models.TextField()),
                ('cancellink', models.TextField()),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproject.account')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('payment', models.TextField()),
                ('paylink', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
