# Generated by Django 3.2.8 on 2021-11-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0004_alter_subscription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='user_seq_no',
            field=models.TextField(default=''),
        ),
    ]
