# Generated by Django 3.2.9 on 2021-11-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0006_auto_20211126_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date',
            field=models.DateField(default='1129'),
        ),
    ]
